/**
 * Validation tests comparing JavaScript DSP implementation against SciPy reference.
 *
 * This test suite loads reference data generated by scipy (using generate_scipy_reference.py)
 * and validates that the JavaScript implementation produces equivalent results.
 *
 * To regenerate reference data:
 *   cd tests
 *   python generate_scipy_reference.py
 *
 * To run these tests:
 *   deno test tests/scipy_validation_test.js
 */

import { assertEquals, assertAlmostEquals } from "jsr:@std/assert";
import { welch, spectrogram } from "../src/dsp.js";

/**
 * Load reference data from JSON file generated by SciPy.
 */
function loadReferenceData() {
  const referenceFile = new URL('./scipy_reference_data.json', import.meta.url);
  const data = JSON.parse(Deno.readTextFileSync(referenceFile));
  return data;
}

/**
 * Compare two arrays element-wise with a relative tolerance.
 * @param {number[]} actual - Actual values from JS implementation
 * @param {number[]} expected - Expected values from SciPy
 * @param {number} rtol - Relative tolerance (default: 1e-6)
 * @param {number} atol - Absolute tolerance (default: 1e-10)
 * @param {string} message - Error message prefix
 */
function assertArrayAlmostEquals(actual, expected, rtol = 1e-6, atol = 1e-10, message = "") {
  assertEquals(actual.length, expected.length,
    `${message} Array length mismatch: ${actual.length} vs ${expected.length}`);

  let maxRelError = 0;
  let maxAbsError = 0;

  for (let i = 0; i < actual.length; i++) {
    const absError = Math.abs(actual[i] - expected[i]);
    const relError = absError / (Math.abs(expected[i]) + atol);

    maxRelError = Math.max(maxRelError, relError);
    maxAbsError = Math.max(maxAbsError, absError);

    // Allow for some numerical differences
    if (absError > atol && relError > rtol) {
      throw new Error(
        `${message} Mismatch at index ${i}: ${actual[i]} vs ${expected[i]} ` +
        `(abs error: ${absError.toExponential(3)}, rel error: ${relError.toExponential(3)})`
      );
    }
  }

  // Print statistics for debugging
  if (message) {
    console.log(`  ${message} - Max abs error: ${maxAbsError.toExponential(3)}, Max rel error: ${maxRelError.toExponential(3)}`);
  }
}

/**
 * Compare 2D arrays (spectrograms) element-wise.
 */
function assert2DArrayAlmostEquals(actual, expected, rtol = 1e-6, atol = 1e-10, message = "") {
  assertEquals(actual.length, expected.length,
    `${message} Spectrogram frequency dimension mismatch`);

  assertEquals(actual[0].length, expected[0].length,
    `${message} Spectrogram time dimension mismatch`);

  let maxRelError = 0;
  let maxAbsError = 0;
  let errorCount = 0;

  for (let f = 0; f < actual.length; f++) {
    for (let t = 0; t < actual[f].length; t++) {
      const absError = Math.abs(actual[f][t] - expected[f][t]);
      const relError = absError / (Math.abs(expected[f][t]) + atol);

      maxRelError = Math.max(maxRelError, relError);
      maxAbsError = Math.max(maxAbsError, absError);

      if (absError > atol && relError > rtol) {
        errorCount++;
        if (errorCount <= 3) { // Show first 3 errors
          console.warn(
            `  Warning: Mismatch at [${f}][${t}]: ${actual[f][t]} vs ${expected[f][t]} ` +
            `(abs: ${absError.toExponential(3)}, rel: ${relError.toExponential(3)})`
          );
        }
      }
    }
  }

  const totalElements = actual.length * actual[0].length;
  const errorRate = errorCount / totalElements;

  console.log(`  ${message} - Max abs error: ${maxAbsError.toExponential(3)}, ` +
    `Max rel error: ${maxRelError.toExponential(3)}, ` +
    `Error rate: ${(errorRate * 100).toFixed(2)}%`);

  // Allow up to 1% of points to have larger errors (due to numerical precision)
  if (errorRate > 0.01) {
    throw new Error(
      `${message} Too many mismatched points: ${errorCount}/${totalElements} (${(errorRate * 100).toFixed(2)}%)`
    );
  }
}

// Load reference data once for all tests
let referenceData;
try {
  referenceData = loadReferenceData();
  console.log("✓ Loaded SciPy reference data");
} catch (e) {
  console.error("Failed to load reference data. Run: python tests/generate_scipy_reference.py");
  throw e;
}

/********************* Welch PSD Validation Tests *********************/

Deno.test("Welch: sine_100hz - default parameters", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.welch.sine_100hz.default;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: two_tone - default parameters", () => {
  const signalData = referenceData.signals.two_tone;
  const ref = referenceData.welch.two_tone.default;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: chirp - default parameters", () => {
  const signalData = referenceData.signals.chirp;
  const ref = referenceData.welch.chirp.default;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: white_noise - default parameters", () => {
  const signalData = referenceData.signals.white_noise;
  const ref = referenceData.welch.white_noise.default;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: sine_100hz - no overlap", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.welch.sine_100hz.no_overlap;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: sine_100hz - high overlap", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.welch.sine_100hz.high_overlap;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: sine_100hz - spectrum scaling", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.welch.sine_100hz.spectrum_scaling;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: sine_with_dc - no detrend", () => {
  const signalData = referenceData.signals.sine_with_dc;
  const ref = referenceData.welch.sine_with_dc.no_detrend;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: sine_100hz - larger nperseg", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.welch.sine_100hz.larger_nperseg;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

Deno.test("Welch: sine_100hz - zero padding (nfft > nperseg)", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.welch.sine_100hz.zero_padding;

  const result = welch(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    nfft: ref.params.nfft,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.psd, ref.psd, 1e-5, 1e-10, "PSD");
});

/********************* Spectrogram Validation Tests *********************/

Deno.test("Spectrogram: sine_100hz - default parameters (psd mode)", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.spectrogram.sine_100hz.default;

  const result = spectrogram(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    mode: ref.params.mode,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.times, ref.times, 1e-10, 1e-12, "Times");
  assert2DArrayAlmostEquals(result.spectrogram, ref.spectrogram, 1e-5, 1e-10, "Spectrogram");
});

Deno.test("Spectrogram: two_tone - default parameters", () => {
  const signalData = referenceData.signals.two_tone;
  const ref = referenceData.spectrogram.two_tone.default;

  const result = spectrogram(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    mode: ref.params.mode,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.times, ref.times, 1e-10, 1e-12, "Times");
  assert2DArrayAlmostEquals(result.spectrogram, ref.spectrogram, 1e-5, 1e-10, "Spectrogram");
});

Deno.test("Spectrogram: chirp - default parameters", () => {
  const signalData = referenceData.signals.chirp;
  const ref = referenceData.spectrogram.chirp.default;

  const result = spectrogram(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    mode: ref.params.mode,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.times, ref.times, 1e-10, 1e-12, "Times");
  assert2DArrayAlmostEquals(result.spectrogram, ref.spectrogram, 1e-5, 1e-10, "Spectrogram");
});

Deno.test("Spectrogram: sine_100hz - magnitude mode", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.spectrogram.sine_100hz.magnitude_mode;

  const result = spectrogram(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    mode: ref.params.mode,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.times, ref.times, 1e-10, 1e-12, "Times");
  assert2DArrayAlmostEquals(result.spectrogram, ref.spectrogram, 1e-5, 1e-10, "Spectrogram");
});

Deno.test("Spectrogram: sine_100hz - high overlap", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.spectrogram.sine_100hz.high_overlap;

  const result = spectrogram(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    mode: ref.params.mode,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.times, ref.times, 1e-10, 1e-12, "Times");
  assert2DArrayAlmostEquals(result.spectrogram, ref.spectrogram, 1e-5, 1e-10, "Spectrogram");
});

Deno.test("Spectrogram: sine_100hz - spectrum scaling", () => {
  const signalData = referenceData.signals.sine_100hz;
  const ref = referenceData.spectrogram.sine_100hz.spectrum_scaling;

  const result = spectrogram(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    mode: ref.params.mode,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.times, ref.times, 1e-10, 1e-12, "Times");
  assert2DArrayAlmostEquals(result.spectrogram, ref.spectrogram, 1e-5, 1e-10, "Spectrogram");
});

Deno.test("Spectrogram: white_noise - magnitude mode no detrend", () => {
  const signalData = referenceData.signals.white_noise;
  const ref = referenceData.spectrogram.white_noise.no_detrend;

  const result = spectrogram(signalData.signal, {
    fs: signalData.fs,
    nperseg: ref.params.nperseg,
    noverlap: ref.params.noverlap,
    mode: ref.params.mode,
    scaling: ref.params.scaling,
    detrend: ref.params.detrend
  });

  assertArrayAlmostEquals(result.frequencies, ref.frequencies, 1e-10, 1e-12, "Frequencies");
  assertArrayAlmostEquals(result.times, ref.times, 1e-10, 1e-12, "Times");
  assert2DArrayAlmostEquals(result.spectrogram, ref.spectrogram, 1e-5, 1e-10, "Spectrogram");
});

console.log("\n✓ All SciPy validation tests completed");
